export const ENDPOINTS = {
	CONFIGURATION: {
		DETAILS: "/configuration",
		COUNTRIES: "/configuration/countries",
		JOBS: "/configuration/jobs",
		LANGUAGES: "/configuration/languages",
		TIMEZONES: "/configuration/timezones",
		PRIMARY_TRANSLATIONS: "/configuration/primary_translations",
	},
	CERTIFICATIONS: {
		MOVIE_CERTIFICATIONS: "/certification/movie/list",
		TV_CERTIFICATIONS: "/certification/tv/list",
	},
	CHANGES: {
		MOVIE_LIST: "/movie/changes",
		PEOPLE_LIST: "/person/changes",
		TV_LIST: "/tv/changes",
	},
	DISCOVER: {
		MOVIE: "/discover/movie",
		TV: "/discover/tv",
	},
	CREDITS: {
		DETAILS: "/credit",
	},
	COMPANIES: {
		DETAILS: "/company",
		ALTERNATIVE_NAMES: "/alternative_names",
		IMAGES: "/images",
	},
	COLLECTIONS: {
		DETAILS: "/collection",
		IMAGES: "/images",
		TRANSLATIONS: "/translations",
	},
	GENRES: {
		MOVIE_LIST: "/genre/movie/list",
		TV_LIST: "/genre/tv/list",
	},
	MOVIES: {
		DETAILS: "/movie",
		ALTERNATIVE_TITLES: "/alternative_titles",
		CREDITS: "/credits",
		EXTERNAL_IDS: "/external_ids",
		KEYWORDS: "/keywords",
		CHANGES: "/changes",
		IMAGES: "/images",
		LATEST: "/latest",
		NOW_PLAYING: "/now_playing",
		POPULAR: "/popular",
		RECOMMENDATIONS: "/recommendations",
		RELEASE_DATES: "/release_dates",
		REVIEWS: "/reviews",
		SIMILAR: "/similar",
		TOP_RATED: "/top_rated",
		TRANSLATIONS: "/translations",
		UPCOMING: "/upcoming",
		VIDEOS: "/videos",
		WATCH_PROVIDERS: "/watch/providers",
	},
	SEARCH: {
		MOVIE: "/search/movie",
		COLLECTION: "/search/collection",
		COMPANY: "/search/company",
		KEYWORD: "/search/keyword",
		MULTI: "/search/multi",
		PERSON: "/search/person",
		TV: "/search/tv",
	},
	TV_SERIES: {
		DETAILS: "/tv",
		AGGREGATE_CREDITS: "/aggregate_credits",
		AIRING_TODAY: "/airing_today",
		ALTERNATIVE_TITLES: "/alternative_titles",
		CHANGES: "/changes",
		CONTENT_RATINGS: "/content_ratings",
		CREDITS: "/credits",
		EPISODE_GROUPS: "/episode_groups",
		EXTERNAL_IDS: "/external_ids",
		IMAGES: "/images",
		KEYWORDS: "/keywords",
		LATEST: "/latest",
		LISTS: "/lists",
		ON_THE_AIR: "/on_the_air",
		POPULAR: "/popular",
		RECOMMENDATIONS: "/recommendations",
		REVIEWS: "/reviews",
		SCREENED_THEATRICALLY: "/screened_theatrically",
		SIMILAR: "/similar",
		TOP_RATED: "/top_rated",
		TRANSLATIONS: "/translations",
		VIDEOS: "/videos",
		WATCH_PROVIDERS: "/watch/providers",
	},
};
